// Generated by https://quicktype.io

export interface RESTCountry {
  data: Data;
}

export interface Data {
  _demo: Demo;
  objects: Object[];
  meta: Meta;
}

export interface Demo {
  message: string;
  signup_url: string;
}

export interface Meta {
  total: number;
  request_id: string;
}

export interface Object {
  names: Names;
  codes: Codes;
  capitals: Capital[];
  flag: Flag;
  region: string;
  subregion: string;
  area: Area;
  assets: any[];
  borders: string[];
  calling_codes: string[];
  cars: Cars;
  classification: Classification;
  continents: string[];
  coordinates: Coordinates;
  currencies: Currency[];
  date: DateClass;
  demonyms: Demonyms;
  descriptions: Descriptions;
  economy: Economy;
  government_type: string;
  landlocked: boolean;
  languages: Language[];
  leaders: Leader[];
  links: ObjectLinks;
  memberships: { [key: string]: boolean };
  number_format: NumberFormat;
  parent: Parent;
  population: number;
  postal_code: PostalCode;
  timezones: string[];
  tlds: string[];
  units: Units;
  uuid: string;
  _meta: MetaClass;
}

export interface MetaClass {
  lastUpdatedTimestamp: number;
}

export interface Area {
  kilometers: number;
  miles: number;
}

export interface Capital {
  attributes: CapitalAttributes;
  coordinates: Coordinates;
  name: string;
}

export interface CapitalAttributes {
  administrative: boolean;
  constitutional: boolean;
  executive: boolean;
  judicial: boolean;
  legislative: boolean;
  primary: boolean;
}

export interface Coordinates {
  lat: number;
  lng: number;
}

export interface Cars {
  driving_side: string;
  signs: string[];
}

export interface Classification {
  dependency: boolean;
  dependency_type: string;
  disputed: boolean;
  iso_status: string;
  sovereign: boolean;
  un_member: boolean;
  un_observer: boolean;
}

export interface Codes {
  alpha_2: string;
  alpha_3: string;
  ccn3: string;
  cioc: string;
  fifa: string;
  fips: string;
  gec: string;
}

export interface Currency {
  code: string;
  name: string;
  symbol: string;
}

export interface DateClass {
  academic_year_start: AcademicYearStart;
  fiscal_year_start: FiscalYearStart;
  start_of_week: string;
}

export interface AcademicYearStart {
  day: number;
  month: number;
}

export interface FiscalYearStart {
  corporate: Corporate;
  government: AcademicYearStart;
  personal: AcademicYearStart;
}

export interface Corporate {
  basis: string;
  day: number;
  month: number;
}

export interface Demonyms {
  eng: DemonymsEng;
  fra: DemonymsEng;
}

export interface DemonymsEng {
  f: string;
  m: string;
}

export interface Descriptions {
  long: string;
  short: string;
}

export interface Economy {
  gini_coefficient: { [key: string]: number };
}

export interface Flag {
  colors: Colors;
  description: string;
  emoji: string;
  html_entity: string;
  unicode: string;
  url_png: string;
  url_svg: string;
}

export interface Colors {
  dominant: string;
  palette: Palette[];
  prominent: string;
  swatches: Swatches;
}

export interface Palette {
  hex: string;
  proportion: number;
}

export interface Swatches {
  dark_muted: null;
  dark_vibrant: null;
  light_muted: string;
  light_vibrant: string;
  muted: string;
  vibrant: string;
}

export interface Language {
  bcp47: string;
  iso639_1: string;
  iso639_2b: string;
  iso639_2t: string;
  iso639_3: string;
  name: string;
  native_name: string;
}

export interface Leader {
  assets: Assets;
  attributes: LeaderAttributes;
  links: LeaderLinks;
  name: string;
  title: string;
  uuid: string;
}

export interface Assets {
  'wikipedia.article.open_graph_image': WikipediaArticleOpenGraphImage;
}

export interface WikipediaArticleOpenGraphImage {
  renditions: Rendition[];
  source: string;
  type: string;
}

export interface Rendition {
  content_hash: string;
  content_type: ContentType;
  filesize: number;
  height: number;
  max_edge: number;
  url: string;
  width: number;
}

export enum ContentType {
  ImageWebp = 'image/webp',
}

export interface LeaderAttributes {
  administers_executive: boolean;
  de_facto_executive: boolean;
  head_of_government: boolean;
  head_of_state: boolean;
  is_representative: boolean;
  pending_office: boolean;
  provisional: boolean;
}

export interface LeaderLinks {
  wikipedia: string;
}

export interface ObjectLinks {
  google_maps: string;
  official: string;
  open_street_maps: string;
  wikipedia: string;
}

export interface Names {
  alternates: any[];
  common: string;
  native: Native;
  official: string;
  translations: { [key: string]: EngValue };
}

export interface Native {
  eng: EngValue;
  fra: EngValue;
}

export interface EngValue {
  common: string;
  official: string;
}

export interface NumberFormat {
  decimal_separator: string;
  thousands_separator: string;
}

export interface Parent {
  alpha_2: string;
  alpha_3: string;
}

export interface PostalCode {
  format: string;
  regex: string;
}

export interface Units {
  measurement_system: string;
  temperature_scale: string;
}
